name: Maven Deploy Action
inputs:
  java-version:
    description: "Java version to use for the release"
    required: true
    default: "21"

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'

    - name: Build and Deploy
      shell: bash
      run: |
        mvn clean package deploy
        echo "Maven deploy completed successfully."
      env:
        GITHUB_TOKEN: ${{ github.token }}