name: Maven Deploy Action

runs:
  using: composite

  steps:
    - name: Deploy
      shell: bash
      run: |
        mvn -B deploy -DskipTests
        echo "Maven deploy completed successfully."
      env:
        GITHUB_TOKEN: ${{ github.token }}