name: Kubernetes Manifest Update Action

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update Manifest
      run: |
        chmod +x "${{ github.action_path }}/main.sh"
        "${{ github.action_path }}/main.sh" \
        "--repo-name ${{ github.event.repository.name }}" \
        "--country ${{ inputs.country }}" \
        "--environment ${{ inputs.environment }}" \
        "--farm ${{ inputs.farm }}" \
        "--container-image ${{ inputs.container-image }}"
      shell: bash

    - name: Commit and push manifest changes
      shell: bash
      run: |
        git add .
        git commit -m "[GITHUB ACTION] - Update Kubernetes manifest with new container image for ${{ github.event.repository.name }}"
        git push origin HEAD