name: Kubernetes Manifest Update Action

inputs:
  country:
    description: 'Country for which the manifest should be updated'
    required: true
  environment:
    description: 'Environment for which the manifest should be updated (e.g., dev, staging, prod)'
    required: true
  farm:
    description: 'Farm for which the manifest should be updated'
    required: true
  container-image:
    description: 'New container image to update in the Kubernetes manifest'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update Manifest
      run: |
        chmod +x "${{ github.action_path }}/main.sh"
        "${{ github.action_path }}/main.sh" \
        --repo-name "${{ github.event.repository.name }}" \
        --country "${{ inputs.country }}" \
        --environment "${{ inputs.environment }}" \
        --farm "${{ inputs.farm }}" \
        --container-image "${{ inputs.container-image }}" \
        --trace
      shell: bash

    - name: Commit and push manifest changes
      shell: bash
      run: |
        git add .
        git commit -m "[GITHUB ACTION] - Update Kubernetes manifest with new container image for ${{ github.event.repository.name }}"
        git push origin HEAD