name: Maven Release Action

inputs:
  python-version:
    description: "Python version to use for the release"
    required: true
    type: string
    default: "3.10"

release:
  runs-on: ubuntu-22.04

  steps:
    - name: Perform Release
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python setup.py sdist bdist_wheel
        twine upload dist/*
