name: Maven Release Action

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version to use for the release"
        required: true
        type: string
        default: "3.10"
  push:
    branches:
      - 'release/**'

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.python-version }}

      - name: Perform Release
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py sdist bdist_wheel
          twine upload dist/*
