name: Docker Build and Push
runs:
  using: composite
  steps:
    - name: Extract version from setup.py
      shell: bash
      id: get_version
      run: |
        if [ -f setup.py ]; then
          VERSION=$(python3 setup.py --version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        elif [ -f pom.xml ]; then
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "No setup.py or pom.xml found. Cannot determine version."
          exit 1
        fi

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Set up Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          ${{ env.VERSION }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          SERVICE_NAME=${{ github.repository }}
          SERVICE_VERSION=${{ env.VERSION }}

    - name: Build Summary
      shell: bash
      run: |
        echo "# Docker Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "**Docker Image**: ghcr.io/${{ github.repository }}:${{ env.VERSION }}  " >> $$GITHUB_STEP_SUMMARY
