name: CI Dispatcher
on:
  push:
    branches:
      - '**'
  workflow_call:
    inputs:
      project-type:
        description: "Select the project type"
        type: string
        required: true
        default: ""
      java-version:
        description: "Java version (if applicable)"
        required: false
        type: string
        default: "21"
      python-version:
        description: "Python version (if applicable)"
        required: false
        type: string
        default: "3.10"
  workflow_dispatch:
    inputs:
      project-type:
        description: "Select the project type"
        required: true
        type: choice
        options:
          - docker-maven
          - docker-python
          - maven
      java-version:
        description: "Java version (if applicable)"
        required: false
        type: string
        default: "21"
      python-version:
        description: "Python version (if applicable)"
        required: false
        type: string
        default: "3.10"
jobs:
  dispatch:
    runs-on: ubuntu-22.04

    steps:
      - name: Run workflow
        uses: actions/github-script@v7
        with:
          github-token: '${{ github.token }}'
          script: |
            const projectType = '${{ github.event.inputs.project-type }}';
            const inputs={}
            
            if(!projectType){
                return;
            }
            
            if(projectType === 'docker-maven' || projectType === 'maven') {
              inputs['java-version'] = '${{ github.event.inputs.java-version }}';
            } else if (projectType === 'docker-python') {
              inputs['python-version'] = '${{ github.event.inputs.python-version }}';
            }
            
            
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: `${projectType}.yml`,
              ref: '${{github.ref_name}}',
              inputs
            })
