name: CI Dispatcher
on:
  workflow_call:
    inputs:
      project-type:
        description: "Select the project type"
        type: string
        required: true
        default: ""
      java-version:
        description: "Java version (if applicable)"
        required: false
        type: string
        default: "21"
      python-version:
        description: "Python version (if applicable)"
        required: false
        type: string
        default: "3.10"

jobs:
  dispatch:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Maven Workflow
        uses: pingmyheart/Ping-Actions/.github/workflows/docker-maven.yml@main
        with:
          java-version: ${{ inputs.java-version }}
        if: "${{ inputs.project-type == 'docker-maven' }}"

      - name: Docker Python Workflow
        uses: pingmyheart/Ping-Actions/.github/workflows/docker-python.yml@main
        with:
          python-version: ${{ inputs.python-version }}
        if: "${{ inputs.project-type == 'docker-python' }}"

      - name: Maven Workflow
        uses: pingmyheart/Ping-Actions/.github/workflows/maven.yml@main
        with:
          java-version: ${{ inputs.java-version }}
        if: "${{ inputs.project-type == 'maven' }}"
