name: CI Dispatcher
on:
  workflow_call:
    inputs:
      project-type:
        description: "Select the project type"
        type: string
        required: true
        default: ""
      java-version:
        description: "Java version (if applicable)"
        required: false
        type: string
        default: "21"
      python-version:
        description: "Python version (if applicable)"
        required: false
        type: string
        default: "3.10"

jobs:
  docker-maven:
    uses: pingmyheart/Ping-Actions/.github/workflows/docker-maven.yml@main
    with:
      java-version: ${{ inputs.java-version }}
    if: ${{ inputs.project-type == 'docker-maven' }}

  docker-python:
    uses: pingmyheart/Ping-Actions/.github/workflows/docker-python.yml@main
    with:
      python-version: ${{ inputs.python-version }}
    if: ${{ inputs.project-type == 'docker-python' }}

  maven:
    uses: pingmyheart/Ping-Actions/.github/workflows/maven.yml@main
    with:
      java-version: ${{ inputs.java-version }}
    if: ${{ inputs.project-type == 'maven' }}

  python-executable:
    uses: pingmyheart/Ping-Actions/.github/workflows/python-executable.yml@main
    with:
      python-version: ${{ inputs.python-version }}
    if: ${{ inputs.project-type == 'python-executable' }}
