name: Python with Docker Aggregated Workflow
on:
  push:
    branches:
      - '**'
  workflow_call:
    inputs:
      python-version:
        description: "Python version (if applicable)"
        required: false
        type: string
        default: "3.10"
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version (if applicable)"
        required: false
        type: string
        default: "3.10"

jobs:
  distribute:
    runs-on: ubuntu-22.04
    steps:
      - name: Import Python Release Action
        uses: pingmyheart/Ping-Actions/.github/actions/python/release@main
        with:
          python-version: '${{ inputs.python-version }}'
        if: startsWith(github.ref_name, 'release/')
