name: Maven with Docker Aggregated Workflow
on:
  push:
    branches:
      - '**'
  workflow_call:
    inputs:
      java-version:
        description: "Java version (if applicable)"
        required: false
        type: string
        default: "21"
  workflow_dispatch:
    inputs:
      java-version:
        description: "Java version (if applicable)"
        required: false
        type: string
        default: "21"

jobs:
  distribute:
    runs-on: ubuntu-22.04
    steps:
      - name: Import Maven Release Action
        uses: pingmyheart/Ping-Actions/.github/actions/maven/release@main
        with:
          java-version: '${{ inputs.java-version }}'
        if: startsWith(github.ref_name, 'release/')

      - name: Import Maven Build and Deploy Action
        uses: pingmyheart/Ping-Actions/.github/actions/maven/deploy@main
        with:
          java-version: '${{ inputs.java-version }}'
        if: ! startsWith(github.ref_name, 'release/')
