name: Python with Docker Aggregated Workflow
on:
  push:
    branches:
      - '**'
  workflow_call:
    inputs:
      python-version:
        description: "Python version (if applicable)"
        required: false
        type: string
        default: "3.10"
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version (if applicable)"
        required: false
        type: string
        default: "3.10"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Import Python Release Action
        uses: ./.github/actions/python/release
