name: Maven Aggregated Workflow
on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version (if applicable)"
        required: false
        type: string
        default: "21"

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Import Maven Release Action
        uses: pingmyheart/Ping-Actions/.github/actions/maven/release@main
        if: startsWith(github.ref_name, 'release/')

      - name: Import Maven Build and Deploy Action
        uses: pingmyheart/Ping-Actions/.github/actions/maven/deploy@main
