name: Maven Aggregated Workflow
on:
  workflow_dispatch:
    inputs:
      java-version:
        description: "Java version (if applicable)"
        required: false
        type: string
        default: "21"
  workflow_call:
    inputs:
      java-version:
        description: "Java version (if applicable)"
        required: false
        type: string
        default: "21"

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Release Action
        uses: pingmyheart/Ping-Actions/.github/actions/maven/release@main
        if: "startsWith(github.ref, 'refs/heads/release/')"

      - name: Maven Build and Deploy Action
        uses: pingmyheart/Ping-Actions/.github/actions/maven/deploy@main
        if: "!startsWith(github.ref, 'refs/heads/release/')"