name: Maven Aggregated Workflow
on:
  push:
    branches:
      - '**'
  workflow_call:
    inputs:
      java-version:
        description: "Java version (if applicable)"
        required: false
        type: string
        default: "21"
  workflow_dispatch:
    inputs:
      java-version:
        description: "Java version (if applicable)"
        required: false
        type: string
        default: "21"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Import Maven Release Action
        uses: pingmyheart/Ping-Actions/.github/actions/maven/release@main
