name: Python Executable Aggregated Workflow
on:
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version (if applicable)"
        required: false
        type: string
        default: "3.10"
  workflow_call:
    inputs:
      python-version:
        description: "Python version (if applicable)"
        required: false
        type: string
        default: "3.10"

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Python Release Action
        uses: pingmyheart/Ping-Actions/.github/actions/python/gitflow-release@main
        if: "startsWith(github.ref, 'refs/heads/release/')"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        if: "startsWith(github.ref, 'refs/tags/v')"

  build-xecutable:
    needs:
      - ci
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        if: "startsWith(github.ref, 'refs/tags/v')"

      - name: Python Build Executable Action
        uses: pingmyheart/Ping-Actions/.github/actions/python/build-executable@main
        if: "startsWith(github.ref, 'refs/tags/v')"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ github.token }}