name: Maven Deploy Executable Action

runs:
  using: composite

  steps:
    - name: Build and Deploy
      shell: bash
      run: |
        mvn clean package deploy
        echo "Maven deploy completed successfully."
      env:
        GITHUB_TOKEN: ${{ github.token }}